import { Router } from 'express';
import { PageService } from '../services/page.service.js';
import * as path from 'path';
import { epubService } from '../services/epub.service.js';
import { HttpStatusCode } from 'axios';
import { jobContainerService } from '../services/jobcontainer.service.js';

const router = Router();

router.post('/', async (req, res, next) => {
    const { url } = req.body;

    if (!url) {
        return res.status(HttpStatusCode.BadRequest).json({ error: 'URL is required' });
    }

    try {
        const [ jobId, repo ] = await jobContainerService.initializeJob();
        const pgs = new PageService(url, repo);
        await pgs.loadPage();

        const content = pgs.article.content;
        const pageTitle = pgs.title;

        const options = {
            title: pageTitle,
            author: 'readify',
            publisher: 'Generated by Node.js',
            version: 3,
            content: [
                {
                    title: pageTitle,
                    data: `<div>${content}</div>`,
                },
            ],
            cover: pgs.downloadedImages[0] || '',
        };

        const epubFilePath = path.join(repo, `${pageTitle}.epub`);
        epubService.generateEpub(options, epubFilePath);
        return res.status(HttpStatusCode.Created).json({ jobId: jobId });
    } catch (error) {
        next(error);
    }
});

export default router;