import { Router } from 'express';
import { PageService } from '../services/page.service.js';
import * as path from 'path';

const router = Router();
const repository = '/app/output/';

router.post('/', async (req, res, next) => {
    const { url } = req.body;

    if (!url) {
        return res.status(400).json({ error: 'URL is required' });
    }

    try {
        const pg = new PageService(url, repository);
        await pg.loadPage();

        const content = pg.article.content;
        const pageTitle = pg.title;

        const options = {
            title: pageTitle,
            author: 'readify',
            publisher: 'Generated by Node.js',
            version: 3,
            content: [
                {
                    title: pageTitle,
                    data: `<div>${content}</div>`,
                },
            ],
            cover: pg._downloadImages[0] || '',
        };
    } catch (error) {
        next(err);
    }
});

export default router;